// <auto-generated />
using System;
using Mercadinho.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mercadinho.Repositorio.Migrations
{
    [DbContext(typeof(MercadinhoContexto))]
    [Migration("20200722150213_SegundaVersão")]
    partial class SegundaVersão
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mercadinho.Dominio.Entidades.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<decimal>("PrecoUnitario");

                    b.Property<int>("Quantidade");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Mercadinho.Dominio.Entidades.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataPedido");

                    b.Property<int>("ProdutoIdProduto");

                    b.Property<int>("VendedorIdVendedor");

                    b.HasKey("IdVenda");

                    b.HasIndex("ProdutoIdProduto");

                    b.HasIndex("VendedorIdVendedor");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Mercadinho.Dominio.Entidades.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("IdVendedor");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("Mercadinho.Dominio.Entidades.Venda", b =>
                {
                    b.HasOne("Mercadinho.Dominio.Entidades.Produto", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutoIdProduto")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mercadinho.Dominio.Entidades.Vendedor", "Vendedor")
                        .WithMany("Vendas")
                        .HasForeignKey("VendedorIdVendedor")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
